# Site settings
author: Kristian Joos
title: I Am Going to Be a Software Engineer, but Why?
header-img: img/home-bg.png
email: kjoos22@gmail.com
copyright_name: Kristian Joos
description: > # this means to ignore newlines until "baseurl:"
  Why I chose to study software engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kjoos22

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
